# Generated by Django 5.2.4 on 2025-07-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("changelog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DataSocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("virtual", models.BooleanField()),
                ("name", models.CharField(max_length=30)),
                (
                    "cable",
                    models.ManyToManyField(
                        blank=True,
                        through="normal.Cable",
                        through_fields=("side_a", "side_b"),
                        to="normal.datasocket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CableChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="normal.cable",
                    ),
                ),
                (
                    "changelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cable_relations",
                        to="changelog.changelog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Console",
            fields=[
                (
                    "datasocket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="normal.datasocket",
                    ),
                ),
                ("bauds", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("normal.datasocket",),
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "datasocket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="normal.datasocket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("normal.datasocket",),
        ),
        migrations.AddField(
            model_name="cable",
            name="side_a",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="normal.datasocket",
            ),
        ),
        migrations.AddField(
            model_name="cable",
            name="side_b",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="normal.datasocket",
            ),
        ),
        migrations.CreateModel(
            name="DataSocketChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasocket_relations",
                        to="changelog.changelog",
                    ),
                ),
                (
                    "datasocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="normal.datasocket",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datasocket",
            name="fkdevice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="normal.device"
            ),
        ),
        migrations.CreateModel(
            name="DeviceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_relations",
                        to="changelog.changelog",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="normal.device",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cable",
            constraint=models.CheckConstraint(
                condition=models.Q(("side_a", models.F("side_b")), _negated=True),
                name="no_self_loops",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cable",
            unique_together={("side_a", "side_b")},
        ),
    ]
