# Generated by Django 5.2.4 on 2025-07-31 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("changelog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DataSocket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("virtual", models.BooleanField()),
                ("name", models.CharField(max_length=30)),
                (
                    "cable",
                    models.ManyToManyField(
                        blank=True,
                        through="normal.Cable",
                        through_fields=("side_a", "side_b"),
                        to="normal.datasocket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CableChangeLog",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="normal_cablechangelog",
                        serialize=False,
                        to="changelog.changelog",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="normal.cable",
                    ),
                ),
            ],
            bases=("changelog.changelog",),
        ),
        migrations.CreateModel(
            name="Console",
            fields=[
                (
                    "datasocket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="normal.datasocket",
                    ),
                ),
                ("bauds", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("normal.datasocket", models.Model),
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "datasocket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="normal.datasocket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("normal.datasocket", models.Model),
        ),
        migrations.AddField(
            model_name="cable",
            name="side_a",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="normal.datasocket",
            ),
        ),
        migrations.AddField(
            model_name="cable",
            name="side_b",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="normal.datasocket",
            ),
        ),
        migrations.AddField(
            model_name="datasocket",
            name="fkdevice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="normal.device"
            ),
        ),
        migrations.CreateModel(
            name="DeviceChangeLog",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="normal_devicechangelog",
                        serialize=False,
                        to="changelog.changelog",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="normal.device",
                    ),
                ),
            ],
            bases=("changelog.changelog",),
        ),
        migrations.CreateModel(
            name="ConsoleChangeLog",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="normal_consolechangelog",
                        serialize=False,
                        to="changelog.changelog",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="normal.console",
                    ),
                ),
            ],
            bases=("changelog.changelog",),
        ),
        migrations.CreateModel(
            name="InterfaceChangeLog",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="normal_interfacechangelog",
                        serialize=False,
                        to="changelog.changelog",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="normal.interface",
                    ),
                ),
            ],
            bases=("changelog.changelog",),
        ),
        migrations.AddConstraint(
            model_name="cable",
            constraint=models.CheckConstraint(
                condition=models.Q(("side_a", models.F("side_b")), _negated=True),
                name="no_self_loops",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cable",
            unique_together={("side_a", "side_b")},
        ),
    ]
