# Generated by Django 5.2.4 on 2025-07-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0001_initial"),
        ("normal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsoleChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="console_relations",
                        to="changelog.changelog",
                    ),
                ),
                (
                    "console",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="normal.console",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterfaceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_relations",
                        to="changelog.changelog",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="normal.interface",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DataSocketChangeLog",
        ),
    ]
